name: Autoupdate
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  check-updates:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
    steps:
      - name: set service account file
        id: save_service_account
        run: echo $SERVICE_ACCOUNT>./serviceAccount.json
      - name: install test dependencies
        id: install_dependencies
        run: sudo npm install firebase-tools nyc mocha eslint typedoc typescript -g
      - name: Install emulator
        run: sudo firebase setup:emulators:firestore
      - name: hotfix firebase (after version 8.9.2, there is a problem with permissions)
        run: sudo chmod 0755 /home/runner/.config/configstore/firebase-tools.json
      - name: Autoupdate
        id: autoupdate
        uses: siarheidudko/autoupdater@v1
        with:
          stages: "npm run lint&&npm run build&&npm run cov&&bash hosting.sh"
      - name: Create Release
        id: create_release
        if: ${{ steps.autoupdate.outputs.updated == 'true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.autoupdate.outputs.version }}
          release_name: Release v${{ steps.autoupdate.outputs.version }}
          body: |
            see [CHANGELOG.md](https://github.com/siarheidudko/firebase-engine/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false
      - name: Set registry npm packages
        id: set_registry
        if: ${{ steps.autoupdate.outputs.updated == 'true' }}
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package to NPM
        id: publish_package_npm
        if: ${{ steps.autoupdate.outputs.updated == 'true' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: The job has failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: /home/runner/.npm/_logs/*
  remove-old-artifacts:
    name: Remove old artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days'
